### PR TITLE
Stop using listeners for data extraction

### LINKED ISSUE #15: Question: how to correctly use the createAndFetch method in combination with an ArrayTransformer MessageCreator
## Background:

I'm going to give an example of my current scenario to better explain the issue I'm facing.

This is my query:
```
final class FetchBla extndes Query {

    /**
     * @Serializer\Type("uuid")
     *
     * @Assert\Type(UuidInterface::class)
     *
     * @var UuidInterface
     */
    private $id;

// other stuff
}
```
As you can see I'm relying on JMS to perform the array tranformation from the `Input` to my query object. The property I'm expecting is called `id`.

This is my command:
```
final class CreateBla
{
    /**
     * @Serializer\Type("uuid")
     * @Serializer\SerializedName(IdGenerator::GENERATED_ID)
     *
     * @Assert\Type(UuidInterface::class)
     * @Assert\NotBlank()
     *
     * @var UuidInterface
     */
    private $id;
```

As you can see, I'm relying on top of chimera's Id generation strategy to generate the resource id, the problem is that when I'm trying to wire this 2 components together in the handler:

```
/**
 * @Chimera\ServiceBus\CommandHandler(handles=CreateForm::class)
 * @Chimera\Routing\CreateAndFetchEndpoint(
 *     path="/forms",
 *      command=CreateForm::class,
 *      name="CreateForm",
 *      redirectTo="GetForm",
 *      query=GetForm::class
 * )
 */
```

When I execute the `createAndFetch`, then the value for the `id` filed assigned to the query is `null` and that's because of the mismatch between the `@Serializer\SerializedName(IdGenerator::GENERATED_ID)` of the command and the simple `id` in the `Query`.
I'm unsure how to proceed on this, wether I'm missing something or wether this is a limitation of Chimera.

Ideally I don't want to change my Query or create any other pre-deserialize hook to handle this scenario.

Thanks in advance.

### PR DESCRIPTION
**Pull request by lcobucci**
Fix #15 

This simplifies the deserialisation engine by moving away from events and allowing users to append data via object decoration.

We should remove the deprecated components on the next release.

@dsantang @rdohms can you please help me ensure that we don't break all your apps?

### CODE REVIEW

**Review by dsantang — APPROVED** [review]
Hey @lcobucci, thanks for looking into this, the change you made does indeed fix the issue.

I also think this solution is really nice in terms of extendibility.

The change you introduced shouldn't affect our existing Clients since it's done in a BC way.

If I'm not mistaken, as an upgrade path, the existing Clients should start removing the:

```
@Serializer\SerializedName(IdGenerator::GENERATED_ID)
```

From the `id` property to be compatible with the next major release.

**Comment by lcobucci** [comment]
> Hey @lcobucci, thanks for looking into this, the change you made does indeed fix the issue.
> 
> I also think this solution is really nice in terms of extensibility.

:tada: 

> The change you introduced shouldn't affect our existing Clients since it's done in a BC way.
> 
> If I'm not mistaken, as an upgrade path, the existing Clients should start removing the:

Correct! There's also the possibility of decorating the decorator (if needed):

```php
$extractor = new AppendGeneratedIdentifier(
    new AppendGeneratedIdentifier(
        new UseInputData()
    ),
    '_input.id'
);
```

That would send both `id` and `_input.id` down to the serialiser - which can be kept until annotations are removed from everywhere.

It's important to remember that, if I'm not mistaken, you had some other event listeners which will need to be migrated to the new way of extracting data - they shouldn't be affected until the removal of the deprecated components, though.

**Comment by lcobucci** [comment]
I'm just thinking about moving the interface and these extractors to `chimera/foundation` since they can be reused by another serialiser if we want.

**Comment by rdohms** [comment]
@lcobucci do you have an example of replacing an injector with this decorator? Just to help migration path, maybe add this to an `Upgrade.md`?

Use case: a injector that uses ` $context->getInput()->getAttribute('some-req-data');` and injects it into `$event->setData`

Or is this not affected?

**Comment by lcobucci** [comment]
That injector doesn't need to be changed after this release, only when we remove the deprecated components.

IMHO this is a good example:

https://github.com/chimeraphp/foundation/blob/master/src/MessageCreator/InputExtractor/AppendGeneratedIdentifier.php#L24-L34

I'll documenting stuff soon but I'm terrible at that so any help is appreciated.

**Comment by rdohms** [comment]
We can help with the docs, also this PR then becomes a bit more self-documenting.

How do we hook up a InputExtractor? is there a new tag?

**Comment by lcobucci** [comment]
The idea is to rely on the [SF DI decorator feature](https://symfony.com/doc/current/service_container/service_decoration.html) (using the interface as decorated service).

Something like:

```xml
        <service id="MyCustomExtractor" decorates="Chimera\MessageCreator\InputExtractor">
            <argument type="service" id=".inner"/>
        </service>
```

**Comment by rdohms** [comment]
Aaah, interesting, did not know that. Nice.

**Pull request merged**
